font_family JetBrainsMono Nerd Font
font_size 13

disable_ligatures yes

cursor_shape block

shell fish
shell_integration no

remember_window_size no
window_padding_width 4

background_opacity 0.80

sync_to_monitor no

