font_family JetBrainsMono Nerd Font
font_size 13
disable_ligatures yes

cursor #f08caf
cursor_text_color #17131a
cursor_shape block

shell fish
shell_integration disabled

remember_window_size no
window_padding_width 6

foreground #f3eee8
background #17131a
background_opacity 0.60
selection_foreground #f3eee8
selection_background #d85a88

sync_to_monitor no

