"$schema" = 'https://starship.rs/config-schema.json'

palette = 'cherry'

format = """
[░▒▓](blossom)\
[ 󰴈 ](fg:void bg:blossom)\
[](fg:blossom bg:cherry)\
$directory\
[](fg:cherry bg:wine)\
$git_branch\
$git_status\
[](fg:wine bg:plum)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:plum bg:void)\
$time\
[ ](fg:void)\
\n$character"""

[palettes.cherry]
void = '#17131a'
plum = '#211923'
wine = '#30202d'
cherry = '#d85a88'
blossom = '#f08caf'
cream = '#f3eee8'
petal = '#c9bdc5'

[directory]
style = "fg:cream bg:cherry"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:petal bg:wine)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:petal bg:wine)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:petal bg:plum)]($style)'

[bun]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:petal bg:plum)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:petal bg:plum)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:petal bg:plum)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:petal bg:plum)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:petal bg:void)]($style)'

